version: '3.8'

networks:
  onprem_custom_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.20.0.0/16

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  reverb-self-hosted-gateway:
    image: revdotcom/reverb-self-hosted:open-gateway-latest
    networks:
      - onprem_custom_network
    depends_on:
      - redis
    ports:
      - "57350:80"
    environment:
      - Initialization__AccessToken=[REVAI_API_KEY]
      - Redis__Database=3
      - Redis__Endpoints=host.docker.internal
      - Runner_LogTemplate=[{Timestamp:HH:mm:ss} {Level:u3}] {Message:lj}{NewLine}    {Properties}{NewLine}{Exception}
      - Revspeech__CompletionQueue=local-dev-gateway
      - Revspeech__SubmissionQueue=local-dev-submission
      - Revspeech__SubmissionQueueMultilingualEnglishSpanish=local-dev-submission-enes      
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
  
  reverb-self-hosted-worker:
    image: revdotcom/reverb-self-hosted:open-en-workers-latest
    depends_on:
      - redis
    ports:
      - "57360:80"
    environment:
      - AccessToken=[REVAI_API_KEY]
      - APPLICATIONNAME=revspeech
      - ASPNETCORE_ENVIRONMENT=onprem
      - InboundQueueName=local-dev-submission
      - RedisConfig__Database=3
      - RedisConfig__Endpoints=host.docker.internal
      - RedisConfig__KeyPrefix=onpremv2
      - Runner_LogTemplate=[{Timestamp:HH:mm:ss} {Level:u3}] {Message:lj}{NewLine}    {Properties}{NewLine}{Exception}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
  
  reverb-self-hosted-spanglish-worker:
    image: revdotcom/reverb-self-hosted:open-multilingual-en-es-workers-latest
    depends_on:
      - redis
    ports:
      - "57365:80"
    environment:
      - AccessToken=[REVAI_API_KEY]
      - APPLICATIONNAME=revspeech
      - ASPNETCORE_ENVIRONMENT=onprem
      - InboundQueueName=local-dev-submission-enes
      - RedisConfig__Database=3
      - RedisConfig__Endpoints=host.docker.internal
      - RedisConfig__KeyPrefix=onpremv2
      - Runner_LogTemplate=[{Timestamp:HH:mm:ss} {Level:u3}] {Message:lj}{NewLine}    {Properties}{NewLine}{Exception}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
  
  reverb-self-hosted-streaming:
    image: revdotcom/reverb-self-hosted:open-streaming-latest
    networks:
      onprem_custom_network:
        ipv4_address: 192.20.0.10
    depends_on:
      - redis
    ports:
      - "57370:80"
    environment:
      - OnPrem__AccessToken=[REVAI_API_KEY]
      - OnPrem__InstanceIp=172.20.0.10
      - OnPrem__Redis__Database=3
      - OnPrem__Redis__Endpoints=host.docker.internal
      - OnPrem__Redis__KeyPrefix=onpremv2
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    restart: always
