global:
  scrape_interval:     15s
  evaluation_interval: 15s

rule_files:
  # - "first.rules"

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']
  - job_name: revspeech_gateway
    static_configs:
      - targets: ["host.docker.internal:57350"]
  - job_name: revspeech_worker
    static_configs:
      - targets: ["host.docker.internal:57360"]
  - job_name: revspeech_spanglish_worker
    static_configs:
      - targets: ["host.docker.internal:57365"]
  - job_name: streaming_worker
    static_configs:
      - targets: ["host.docker.internal:57370"]
